### ISSUE TITLE
Usage with Islands?

### ISSUE THREAD

**Issue by KjellConnelly** [lxsmnsyc/solid-headless#20]
Hi! I'm fairly new to both headless ui (react and solid), so this may be somewhat obvious, but I'm trying to get `solid-headless` to work with solid. I am able to get this library to work using regular SSR, as well as SPA. I am also able to get reactive components to work using islands when using simple Signals. For example:

```ts
// vite.config.ts
solid({
  islands: true, 
  islandsRouter: true,
}),
```

```tsx
// Counter.tsx
import { createSignal } from "solid-js";

export default function Counter() {
  const [count, setCount] = createSignal(0);
  return (
    <button class="increment" onClick={() => setCount(count() + 1)}>
      Clicks: {count()}
    </button>
  );
}
```

```tsx
// index.tsx
import { unstable_island } from 'solid-start'
const Counter = unstable_island(()=>import("./Counter"))

export default function App() {
  return (
    <div>
      <Counter />
    </div>
  )
}
```

Unfortunately, I am unable to do this with solid-headless:

```tsx
const { Popover } = unstable_island(()=>import("solid-headless"))
```

Looking further, it seems that `unstable_island` needs a default export, so I tried wrapping

```tsx
// WrappedPopover.tsx
export { Popover as default } from "solid-headless"
```

```tsx
// index.tsx
import { unstable_island } from 'solid-start'
const WrappedPopover = unstable_island(()=>import("./WrappedPopover"))

export default function App() {
  return (
    <div>
      <WrappedPopover>
        {/* other elements that were also exported */}
      </WrappedPopover>
    </div>
  )
}
```

Two outcomes occur. If I directly wrap the headless elements, then my entire page shows blank.

But if I import a component inside of `index.tsx` which uses unstable islands to import, the page shows, but the component becomes static and has no reactivity.

**Comment by lxsmnsyc** [comment]
I think what I can only recommend you here is to create another module that imports the solid-headless component, export it as default, then import the new module as an island

**Comment by KjellConnelly** [comment]
@lxsmnsyc Isn't that what I already did in the code above? 

```tsx
// WrappedPopover.tsx
export { Popover as default } from "solid-headless"
```

```tsx
// index.tsx
import { unstable_island } from 'solid-start'
const WrappedPopover = unstable_island(()=>import("./WrappedPopover"))

export default function App() {
  return (
    <div>
      <WrappedPopover>
        {/* other elements that were also exported */}
      </WrappedPopover>
    </div>
  )
}
```

Or did I miss something in that set of steps?

**Comment by lxsmnsyc** [comment]
Hmm I missed that on first read. TBF I think the whole popover and its children should be made as a separate component, then import that component as an island. I'm not really sure about the island specifics for SolidStart so I'm not sure if my answer is accurate or helpful.

**Comment by KjellConnelly** [comment]
It's a bit weird because I tried both solutions, but I just noticed that when I run on dev, the headless components aren't reactive, but once I `npm run build`, `npm run start`, they are reactive. Not sure what the deal here is...

**Comment by lxsmnsyc** [comment]
What I'm saying is instead of doing something like

```js
import { unstable_island } from 'solid-start'
const WrappedPopover = unstable_island(()=>import("./WrappedPopover"))

export default function App() {
  return (
    <div>
      <WrappedPopover>
        {/* other elements that were also exported */}
      </WrappedPopover>
    </div>
  )
}
```

You should do

```js
import { unstable_island } from 'solid-start'
const WrappedPopoverIsland = unstable_island(()=>import("./WrappedPopoverIsland "))

export default function App() {
  return (
    <div>
      {/* component contains child into the island */}
      <WrappedPopoverIsland />
    </div>
  )
}
```

**Comment by KjellConnelly** [comment]
Finally got it working. Turns out that I had imported a solid component as a non-default export which was from a Server component. I think in the Documentation repo here, they do export the `<A>` component as default from solid-start, and have to import it into an island. So I ended up having to do the same thing.

## Before:

### App.tsx
   - `const FeaturesDesktop = unstable_island(()=>import("./FeaturesDesktop")`
   - `export function FeatureComponent(props) {`
   - `function FeaturesMobile() {`

### FeaturesDesktop.tsx
   - `import { FeatureComponent } from './App'`
   
## After:

### App.tsx
   - `const FeaturesDesktop = unstable_island(()=>import("./FeaturesDesktop")`
   - `import FeatureComponent from './FeatureComponent'`
   - `function FeaturesMobile() {`

### FeaturesDesktop.tsx
   - `import FeatureComponent from './FeatureComponent'`

### FeatureComponent.tsx
   - `export default function FeatureComponent(props) {`

## Explanation

Poor architecture, but whatever - App.tsx uses the Mobile Features component, and imports the Desktop Features Component as an island. Both Mobile and Desktop show the same FeatureComponent, but it is displayed differently. On Mobile, it is static, and on Desktop, it is reactive. 

I may have missed a few steps along the way, but this is the solution I have come up with and hopefully it helps others who get stuck in the same situation.
