### ISSUE TITLE
Do you have alternative for headlessUI Switch?

### ISSUE THREAD

**Issue by quantuminformation** [lxsmnsyc/solid-headless#23]
Is it just <Toggle> that I can swap out this usage of headlessUi <switch>?

<img width="736" alt="image" src="https://user-images.githubusercontent.com/216566/208076113-3b0a5810-d138-4b4c-8ece-e78397fa3f21.png">

**Comment by lxsmnsyc** [comment]
The closest would be the Toggle component.
