### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by lxsmnsyc** [lxsmnsyc/solid-headless#5]
Thinking of rebranding this library into a new one, probably a catchy name that reminds us of Headless UI and Solid. `solid-headless` isn't really helpful at all and I want this library to be distinct from the existing Headless UI (by Adam Wathan, great author) because of the library's scope and features.

**Comment by aecea** [comment]
solid-podium
solid-ramp
solid-lift-ui
solid-fearless

**Comment by davedbase** [comment]
Here's a backlogged list of names I've kept in my notes (plus some additinons:

Metal
Solidness
ScaffoldUI
Molecular
Metallic
Interfaced
Amorphous/Morphous (in science a solid without a form)
CompositeUI
DependUI
SoliderUI
MatterUI (as in states of matter :-p)
Form
MouldedUI
ForgedUI
Malleable
Pliable

These are just random you may want to think about what differentiates the project from others and use the name to reinforce that. If not just bit an arbitrary name that sounds fancy/nice to you.

**Comment by LXSMNSYC** [comment]
> Amorphous/Morphous (in science a solid without a form)

oooh this one, I really like this, but I'll probably consider the others as well

**Comment by LXSMNSYC** [comment]
Seems like I'll go with PolyUI. I'll rebrand once 1.0 version is ready for release, meanwhile, I'll slowly deprecate `solid-headless` in favor of the new package name. Thanks @davedbase !

**Comment by lxsmnsyc** [comment]
I've decided on a new name 🤣
